name: test
on:
 push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/achieve-3000/core-infra:latest
      credentials:
        username: ci-a3k
        password: ${{ secrets.CI_PAT }}
      steps:
        - name: actor
          run: terraform -v